### ISSUE TITLE
MemFree frontend start problem

### ISSUE THREAD

**Issue by jmwei** [memfreeme/memfree#1]
I clone the issue, when i run, this problem happened 
![image](https://github.com/user-attachments/assets/f0543883-6694-444b-9d9e-d992df71aa9b)

**Comment by ahaapple** [comment]
1. you need to  create a redis database in https://upstash.com/docs/redis/overall/getstarted and get the UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN.

2. I am working on the documentation for setting up a local development environment. And one-click deployment of the production environment

**Comment by ahaapple** [comment]
This is the env example file

```

# Upstash Redis (Required)
UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=



# Auth (Required)
AUTH_SECRET=
# Auth Providers (Optional)
AUTH_GITHUB_ID=
AUTH_GITHUB_SECRET=
# Auth Providers (Optional)
AUTH_GOOGLE_ID=
AUTH_GOOGLE_SECRET=

NEXT_PUBLIC_APP_URL="http://localhost:3000"



# Basical internet search

# https://zeabur.com/templates/77FSH6
SEARXNG_URL=
# https://serper.dev/
SERPER_API_KEY=
# OpenAI API
OPENAI_API_KEY=




# Hyride AI search

# the vector service host
VECTOR_HOST=
# the quque service host
QUEUE_URL="https://xxx.com/api/"
# the api token for the vector, quque and embedding service
API_TOKEN=




# subscription (optional)
BUTTONDOWN_API_KEY =

# Axiom log (optional)
AXIOM_TOKEN=

# Stripe (optional)
STRIPE_API_KEY =
STRIPE_WEBHOOK_SECRET =
NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID =
NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID =
NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID =
NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID =
```

**Comment by jmwei** [comment]
thanks， i will try again

**Comment by jmwei** [comment]
thanks，project can be running. i will try vercel

**Comment by ahaapple** [comment]
https://www.memfree.me/docs/one-click-deploy-ai-search    You could one click to get your Own Hybrid AI Search Engine now  welcome to try
