### ISSUE TITLE
[Bug] Sidebar in middle of screen

### ISSUE THREAD

**Issue by sanketshinde3001** [memfreeme/memfree#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Goto - https://www.memfree.me/pricing

here the sidebar showing between screen. Also those 3 cards not clickable.

### Expected behavior

 - The sidebar should visible normally to right.
 - Those 3 cards should clickable to improve User Experience.

### Add Screenshots

![image](https://github.com/user-attachments/assets/da57c5e2-7f0b-4df2-aa7e-34fd166ca39f)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by malavshah9** [comment]
@ahaapple Please assign this issue to me

**Comment by malavshah9** [comment]
Just to be clear, it is not the sidebar but the scrollbars.

**Comment by ahaapple** [comment]
@malavshah9 Thank you.

**Comment by sanketshinde3001** [comment]
@malavshah9 I was waiting for getting this issue assign ;-/ 
and you made pr also
