### ISSUE TITLE
[Documentation Update]: remove redundant branches from readme.yml file.

### ISSUE THREAD

**Issue by RishonVFernandes** [memfreeme/memfree#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

remove unnecessary branches from readme.yml file. Branch name: Auto-Translation.

### Suggested Change

remove unnecessary branches from readme.yml file

### Rationale

No need for that branch.

### Urgency

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by ahaapple** [comment]
@RishonVFernandes Assigned, thanks.
