### ISSUE TITLE
[Documentation Update]: On mobile screen, the 'AI Generate UI Now' button isn't displaying properly

### ISSUE THREAD

**Issue by krushnarout** [memfreeme/memfree#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The 'AI Generate UI Now' button does not display correctly when viewed on a mobile screen.

https://github.com/user-attachments/assets/7490592c-fbbc-4555-92e7-d7d1dffb477c

### Suggested Change

We can give padding in bottom.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by ahaapple** [comment]
@krushnarout thanks
