### ISSUE TITLE
Support multi-language readme files

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#14]
Current, the readme file only supports English version, we could support other language version. such as Chinese.

**Comment by Brijeshthummar02** [comment]
@ahaapple Sure just do leeme know which language you needed.

**Comment by ahaapple** [comment]
I think you could Chinese language first, or other your favorite language. thank you

**Comment by moli-debugger** [comment]
@ahaapple I have created the readme fiile for Chinese and raised the PR.

FYR, https://github.com/memfreeme/memfree/pull/55#issuecomment-2424141099

Please note that I need approval to create readme file for below mentioned languages. so kindly approve to create readme for other supporting languages and assign this task to me. 

Thank you.

- [ ] German
- [ ]  French
- [ ]  Spanish
- [ ]  Japanese
- [ ] Arabic.

**Comment by ahaapple** [comment]
@moli-debugger done. Thank you.

**Comment by moli-debugger** [comment]
Thank you @ahaapple, I will continue to work on other languages.

**Comment by moli-debugger** [comment]
@ahaapple  Added readme file for below mentioned lanaguages and raised the PR.

FYR, https://github.com/memfreeme/memfree/pull/62

Languages

-  German
-  French
-  Spanish

**Comment by ahaapple** [comment]
@moli-debugger The number of languages ​​is sufficient now. Thank you very much.
