### ISSUE TITLE
Support one click deploy on Railway

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#16]
Support on click deploy on Railway: https://railway.app/templates

you could refer to https://www.memfree.me/docs/one-click-deploy-ai-search

**Comment by KhushiSharma0313** [comment]
Can you explain a bit more about the issue, and your expectation when it's solved.

**Comment by ahaapple** [comment]
Like https://zeabur.com/templates/CE71SC?referralCode=memfree

We could add a template in Railway for MemFree, then the user could one click deploy memfree on railway.
