### ISSUE TITLE
Support on click deploy on Netlify

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#19]
Support on click deploy on Netlify: https://www.netlify.com/

you could refer to https://www.memfree.me/docs/one-click-deploy-ai-search

**Comment by Riyan-Mo** [comment]
@ahaapple Where to include the button for deploying?

**Comment by ahaapple** [comment]
you could include the button in the readme.md file. like Vercel and Zeabur deploy button. Thanks.

**Comment by Riyan-Mo** [comment]
I added the button but apparently it is showing build error while deploying. My guess is I haven't included the redis key for deploying.
![image](https://github.com/user-attachments/assets/4c30c4cd-c7de-46d0-b007-3d7b68a0efa2)

**Comment by ahaapple** [comment]
Yes. you could get the redis key in here: https://upstash.com/docs/redis/overall/getstarted  which is free.

**Comment by Riyan-Mo** [comment]
But wouldn't it expose the key. Since I have to add it to the README file?

**Comment by Riyan-Mo** [comment]
Here is the pull request: https://github.com/memfreeme/memfree/pull/39

**Comment by ahaapple** [comment]
@Riyan-Mo 

Hi, You don't need to expose the key, just set the name of the environment variable that must be configured in the URL

The following vercel deployment url：
```
https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fmemfreeme%2Fmemfree&env=UPSTASH_REDIS_REST_URL%2CUPSTASH_REDIS_REST_TOKEN%2COPENAI_API_KEY%2CMEMFREE_HOST%2CAUTH_SECRET%2CAPI_TOKEN&envDescription=https%3A%2F%2Fgithub.com%2Fmemfreeme%2Fmemfree%2Fblob%2Fmain%2Ffrontend%2Fenv-example&project-name=memfree&repository-name=memfree&demo-title=MemFree&demo-description=MemFree+%E2%80%93+Hybrid+AI+Search+Engine&demo-url=https%3A%2F%2Fwww.memfree.me%2F&demo-image=https%3A%2F%2Fwww.memfree.me%2Fog.png&root-directory=frontend&teamSlug=memfree
```

I searched on memfree and found that netlify should support the following way of passing environment variables. You can test it to confirm. Thank you.
```

https://app.netlify.com/start/deploy?repository=https://github.com/memfreeme/memfree&create_from_path=frontend/&env.API_KEY=your_api_key&env.DEBUG=true

```

**Comment by Riyan-Mo** [comment]
Yes thank you. I will add it.
