### ISSUE TITLE
how to set SearXNG url

### ISSUE THREAD

**Issue by maximdymchenko** [memfreeme/memfree#2]
how to set SearXNG url

**Comment by ahaapple** [comment]
1.  You could  one click deploy SearXNG by  https://zeabur.com/templates/77FSH6
2. You could deploy SearXNG with docker: https://docs.searxng.org/admin/installation-docker.html#installation-docker
3. I am working on a complete memfree backend one-click deployment template, I will update the documentation later

**Comment by ahaapple** [comment]
https://www.memfree.me/docs/one-click-deploy-ai-search    You could one click to get your Own Hybrid AI Search Engine now.  welcome to try
