### ISSUE TITLE
Issue Title: Sidebar Icons Not Displaying on Hover

### ISSUE THREAD

**Issue by kekubhai** [memfreeme/memfree#23]
I'm experiencing an issue with my sidebar where the icons are not appearing when I hover over them. This makes it difficult to navigate and understand the functionality of each option. I've tried refreshing the page, clearing my browser cache, and checking for any recent updates, but the problem persists.

**Comment by ahaapple** [comment]
<img width="123" alt="Screenshot 2024-10-18 at 7 26 31 PM" src="https://github.com/user-attachments/assets/b42c354d-2726-41cb-8857-a4d05e427f92">

I want to confirm, do you mean the icon is not displayed, or the icon prompt is not displayed? What is your browser and operating system?

**Comment by ahaapple** [comment]
Could you provide a screenshot?

**Comment by kekubhai** [comment]
In the dark mode the icons are not recognised properly. That was what I was referring to.

**Comment by ahaapple** [comment]
OK， I will fix it today.

**Comment by ahaapple** [comment]
<img width="114" alt="Screenshot 2024-10-18 at 8 46 33 PM" src="https://github.com/user-attachments/assets/d95a5a3b-60ce-4caf-9228-867935b2b2c1">
Could you please provide a screenshot so I can confirm the cause of this issue ? Because my computer's dark mode also displays normally. Thanks.

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by ahaapple** [comment]
@Aditya-PS-05 assigned. could you reproduce this issue?

**Comment by Aditya-PS-05** [comment]
I ran `npm run prettier` as a result various other files got formated. 
If you have any problem with it, I will fix it. 
Thanks
