### ISSUE TITLE
Add  github star history to README.md file

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#25]
You could add it:

```
## Star History

[![Star History Chart](https://api.star-history.com/svg?repos=memfreeme/memfree&type=Date)](https://star-history.com/#memfreeme/memfree&Date)
```

## Star History

[![Star History Chart](https://api.star-history.com/svg?repos=memfreeme/memfree&type=Date)](https://star-history.com/#memfreeme/memfree&Date)

**Comment by Brijeshthummar02** [comment]
@ahaapple i can do it, assign me to the task.

**Comment by ahaapple** [comment]
Thank you for your contribution, looking forward to your PR

**Comment by Brijeshthummar02** [comment]
@ahaapple do i Add the following section at an appropriate place in your README.md, typically towards the end after the credits or before the license section, is it ok or you can suggest me where you wanted specifically.

**Comment by ahaapple** [comment]
@Brijeshthummar02 which is good, please go ahead.

**Comment by Brijeshthummar02** [comment]
@ahaapple we can close this as it's completed.
