### ISSUE TITLE
Add contributor images  to  README.md file 

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#26]
```
## Special Thanks

### Contributors

<a href="https://github.com/memfreeme/memfree/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=memfreeme/memfree" />
</a>
```

### Contributors

<a href="https://github.com/memfreeme/memfree/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=memfreeme/memfree" />
</a>

**Comment by Virtual4087** [comment]
@ahaapple I would like to work on this

**Comment by ahaapple** [comment]
@Virtual4087 Thank you for your contribution, looking forward to your PR
