### ISSUE TITLE
How to Search / Ask my personal docs ?

### ISSUE THREAD

**Issue by wuhuzi** [memfreeme/memfree#3]
Are there any use cases for searching/asking documents?
I found search/ask func only internet info source.

**Comment by ahaapple** [comment]
Thanks for your support. Currently, the supported personal data sources are mainly bookmarks and web pages. We will soon support markdown files, pdf, doc, and notion documents. It should be released next week.

**Comment by ahaapple** [comment]
https://feedback.memfree.me/changelog/support-indexing-and-ai-search-local-files

We have supported it, welcome try and feedback.
