### ISSUE TITLE
Add issue template files

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#31]
you could refer to

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

https://github.com/devspace/awesome-github-templates

you could add the  template files to  template file .github/ISSUE_TEMPLATE

**Comment by Brijeshthummar02** [comment]
@ahaapple sure, i would take this issue, assign me.
