### ISSUE TITLE
Add a pull request template file

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#33]
You could refer to https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

add a  .github/PULL_REQUEST_TEMPLATE.md

**Comment by Riyan-Mo** [comment]
I would like to take on this.

**Comment by ahaapple** [comment]
Thank you for your contribution, looking forward to your PR

**Comment by ahaapple** [comment]
https://github.com/memfreeme/memfree/pull/56 resolve it.
