### ISSUE TITLE
Feature Request: Automated Greeting for Issues and Pull Requests

### ISSUE THREAD

**Issue by Virtual4087** [memfreeme/memfree#34]
I'd like to propose adding a GitHub Actions workflow to automatically greet users when they open issues or pull requests. This can help enhance the contributor experience by acknowledging their efforts immediately and fostering a more engaging community.

**Comment by ahaapple** [comment]
Great idea, would you like to do this job? Thanks

**Comment by Virtual4087** [comment]
Yes please assign it to me

**Comment by ahaapple** [comment]
done, thanks.
