### ISSUE TITLE
Automatically add "Hacktoberfest" label to new issues

### ISSUE THREAD

**Issue by Virtual4087** [memfreeme/memfree#37]
It would be cool to have a workflow that automatically adds the "hacktoberfest" label to every new issue created in this repo. This way, we won’t have to manually add the label to each issue during Hacktoberfest. It’ll make things smoother for contributors and help them easily find issues they can work on.

**Comment by Brijeshthummar02** [comment]
@Virtual4087 i can add it. it suppose to be added at .github/workflows/add-hacktoberfest-label.yml.

@ahaapple should i proceed.

**Comment by ahaapple** [comment]
@Virtual4087  Hi，Do you plan to complete this issue yourself? Or do you think it can be done by Brijeshthummar02?

**Comment by Virtual4087** [comment]
I can do it

**Comment by ahaapple** [comment]
@Brijeshthummar02 Sorry, since it was Virtual 4087 who created the issue and he wanted to complete it himself, I assigned it to him. I hope you understand. You can choose other open issues, thank you.
