### ISSUE TITLE
Beautify the default auth error page

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#42]
The page is https://www.memfree.me/api/auth/error

you could generate the page in https://www.memfree.me/generate-ui

the config the error page in `frontend/auth.ts`

```
    pages: {
        signIn: '/login',
        verifyRequest: '/verify',
        error: '/auth-error'
    },
```

**Comment by Riyan-Mo** [comment]
I would like to work on this.

**Comment by ahaapple** [comment]
@Riyan-Mo Thank you. you could refer to this doc:  https://authjs.dev/guides/pages/error

**Comment by Riyan-Mo** [comment]
@ahaapple I have created the page but I don't know in which directory to place it.

**Comment by ahaapple** [comment]
@Riyan-Mo Hi, you could put it in  frontend/app/[locale]/(marketing) dir. like login page and vefiry page. thanks.

**Comment by Riyan-Mo** [comment]
I was thinking the same. Thank you. I'll add it.
