### ISSUE TITLE
Add a Enhancement issue template

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#43]
Enhancement
<img width="1272" alt="Screenshot 2024-10-19 at 7 22 27 PM" src="https://github.com/user-attachments/assets/7b63ec03-3d62-46fb-919c-9a8505a7297b">

Current, we don't have a Enhancement issue template, we should have one.

**Comment by sank8-2** [comment]
Hi @ahaapple, assign this to me.

**Comment by ahaapple** [comment]
Thank you for your contribution, looking forward to your PR

**Comment by sank8-2** [comment]
@ahaapple Hey, I have raised a PR, please review it

**Comment by ahaapple** [comment]
@sank8-2 merged. thank you.
