### ISSUE TITLE
Fix memfree.me pagespeed Accessibility issues

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#44]
https://pagespeed.web.dev/analysis/https-www-memfree-me/m78c4pnmj2?form_factor=desktop

- Buttons do not have an accessible name
- Links do not have a discernible name
- Background and foreground colors do not have a sufficient contrast ratio.

**Comment by ASANIYAN** [comment]
@ahaapple Hello. I would love to work on this issue. Kindly assign it to me.

**Comment by ahaapple** [comment]
@ASANIYAN Assigned, Thanks.

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by ASANIYAN** [comment]
@ahaapple I can't seem to access the following sites: 

- https://upstash.com/
- https://serper.dev/

I need to get their API keys. Do you have any idea why it's not going through?

**Comment by ahaapple** [comment]
@ASANIYAN  Both websites are normal. Maybe you can try VPN or proxy.

**Comment by ASANIYAN** [comment]
@ahaapple
