### ISSUE TITLE
[Feature Request] Adding pre-commit hooks

### ISSUE THREAD

**Issue by sank8-2** [memfreeme/memfree#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of pre-commit hooks for linters and code formatting.

### Use Case

Code optimisation

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by ahaapple** [comment]
@sank8-2  Great idea. Are you willing to do this job?

**Comment by sank8-2** [comment]
Yes, please assign it

**Comment by sank8-2** [comment]
@ahaapple Please check it

**Comment by ahaapple** [comment]
These are two related issues:

https://github.com/memfreeme/memfree/issues/51

https://github.com/memfreeme/memfree/issues/50

**Comment by sank8-2** [comment]
Ok
