### ISSUE TITLE
[Feature Request] Show time and message number in the search history list

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Show time and message number in the search history list

### Use Case

let the user know the  time and message number info

### Add Screenshots

<img width="286" alt="Screenshot 2024-10-20 at 10 47 31 AM" src="https://github.com/user-attachments/assets/c7d4c2a9-9d43-4d4d-a019-46f2ce3d0fe5">
<img width="274" alt="Screenshot 2024-10-20 at 10 50 55 AM" src="https://github.com/user-attachments/assets/7d2d6613-e31a-4c02-94d0-1740d4b52cc7">

The left side is the current one, we can change it to something similar to the right side

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by aafaris** [comment]
Hi @ahaapple, I would like to work on this. Please do assign, thanks!

**Comment by ahaapple** [comment]
@aafaris assigned, thanks.

**Comment by aafaris** [comment]
Hi @ahaapple, please assist to add "hacktoberfest-accepted" label to my PR for Hacktober 2024, thank you!

**Comment by ahaapple** [comment]
done. thank you.
