### ISSUE TITLE
Make the contributors' avatars in the readme file updated in a timely manner

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#72]
The readme file now shows contributors' avatars, but it hasn't been updated in a few days. please fix it
```
## Thanks to all Contributors

<p align="left">
 <a href="https://github.com/memfreeme/memfree/graphs/contributors">
  <img src="https://contributors-img.web.app/image?repo=memfreeme/memfree" />
 </a>
</p>
```

**Comment by GayanKod** [comment]
Hi!

I’d like to take a look at this issue. I’ll investigate why the contributors’ avatars haven’t been updated and work on fixing it. I’ll keep you posted on my progress.

Thanks!

**Comment by GayanKod** [comment]
You should try [allcontributors.org](https://allcontributors.org/)

**Comment by ahaapple** [comment]
@GayanKod Thank you, I will try

**Comment by ahaapple** [comment]
Seems a bit complicated，

**Comment by DDibyajyot** [comment]
I could try to set up a github action for this?

**Comment by ahaapple** [comment]
@DDibyajyot I previously guessed that there was a cache or it was updated daily. The key is that it has been a few days since the first image was generated, and there is still no update. We can wait a little longer.

**Comment by DDibyajyot** [comment]
Upon investigating, it takes around 2 weeks for this to update, if we are fine with updating every 2 weeks then it shouldnt be an issue, we could have a look at https://github.com/jaywcjlove/github-action-contributors if there's any other issue

**Comment by ahaapple** [comment]
OK, thank you. If so, I think we don't need the github action for it, What do you think?

**Comment by aniruddhaadak80** [comment]
If the contributors-img service does not update automatically, consider using the following alternative:

## Thanks to all Contributors

<p align="left">
  <a href="https://github.com/memfreeme/memfree/graphs/contributors">
    <img src="https://opencollective.com/memfree/contributors.svg?width=890" />
  </a>
</p>

**Comment by prathamesh424** [comment]
@ahaapple  assign this issue to me

**Comment by ahaapple** [comment]
@prathamesh424  Hi,  https://contrib.rocks/image?repo=memfreeme/memfree I have confirmed that contrib.rocks will be updated, but the cycle is longer, which is acceptable at present, so we can close this issue first, thank you
