### ISSUE TITLE
[Documentation Update]: Incomplete installation guide for bun while setting up the project.

### ISSUE THREAD

**Issue by Riyan-Mo** [memfreeme/memfree#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The existing setup guide in README.md doesn't provide complete guide for installing and setting up bun which results in this error: [Bun command not found after running installation script](https://stackoverflow.com/questions/72902668/bun-not-found-after-running-installation-script).

### Suggested Change

Include the command to add bun to path.

### Rationale

While following the current setup guide, the user will encounter error while setting up bun.

### Urgency

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by ahaapple** [comment]
@Riyan-Mo Are you willing to do this work?

**Comment by Riyan-Mo** [comment]
@ahaapple yes.
