### ISSUE TITLE
[Documentation Update]: 

### ISSUE THREAD

**Issue by johnson7788** [memfreeme/memfree#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Both vector and frontend directory have env-example. not env.example.
Change 
cp env.example .env 
To 
cp env-example .env

### Suggested Change

Both vector and frontend directory have env-example. not env.example.
Change 
cp env.example .env 
To 
cp env-example .env

### Rationale

Both vector and frontend directory have env-example. not env.example.
Change 
cp env.example .env 
To 
cp env-example .env

### Urgency

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by ahaapple** [comment]
@johnson7788 thanks

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by prathamesh424** [comment]
@ahaapple assign this issue to me
