### ISSUE TITLE
 Request to Replace OpenAI Base URL with Environment Variable

### ISSUE THREAD

**Issue by lijiajun1997** [memfreeme/memfree#8]
Hello,

I would like to propose an enhancement to the project by allowing the OpenAI base URL to be set as an environment variable. This change would enable us to easily switch to third-party services that convert requests to the OpenAI API format.

Proposed Changes:
Introduce a new environment variable, for example, OPENAI_BASE_URL, which would allow users to specify their own OpenAI API endpoint.
Update the codebase to use this environment variable when making requests to the OpenAI API.
Benefits:
Flexibility to use different OpenAI-compatible services.
Easier integration with third-party APIs that mimic OpenAI's functionality.
Example:
OPENAI_BASE_URL=https://api.example.com/v1
Thank you for considering this request! I believe this enhancement would greatly benefit users who want to utilize alternative OpenAI-compatible services.

**Comment by ahaapple** [comment]
I will support it today.
