### ISSUE TITLE
[Documentation Update]: Auto update all translated versions of the readme file using github actions.

### ISSUE THREAD

**Issue by Riyan-Mo** [memfreeme/memfree#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Using the following: [Translate-Github-Readme](https://github.com/ephraimduncan/translate-readme) we can set it to autotranslate the README file to other languages.

### Suggested Change

null

### Rationale

If implemented any changes to the documentation will only be need to be made once.

### Urgency

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by Riyan-Mo** [comment]
@ahaapple If it's ok with you I would like to work on this.

**Comment by ahaapple** [comment]
@Riyan-Mo  This is what I wanted to do, thanks
