### ISSUE TITLE
Feature/Apply Prettier to Ensure Consistent Styling Across Files

### ISSUE THREAD

**Issue by Aditya-PS-05** [memfreeme/memfree#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The files are not formated and are not following `prettier` standard.

### Use Case

Not much but open-source repos standard.

### Benefits

Helps in maintaining clean and formated code.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by ahaapple** [comment]
@Aditya-PS-05 Assigned, Thank you.
