### ISSUE TITLE
Optimize the time display format of historical messages

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#89]
<img width="293" alt="Screenshot 2024-10-24 at 4 59 25 PM" src="https://github.com/user-attachments/assets/971c0719-c02f-4e83-a935-076ac10bd8be">

- Within an hour, display the number of minutes ago
- Within a day, display the number of hours ago
- Within a week, display the number of days ago
- More than a week, display the full time

**Comment by TilteD24** [comment]
I would like to work on it. Can you mention the related file to this issue ?

**Comment by ahaapple** [comment]
@TilteD24 
This file:
frontend/components/sidebar/sidebar-item.tsx

You could add a util function in  frontend/lib/utils.ts, then replace the following code:

```
                    {!isActive && <span>{format(new Date(search.createdAt), 'MMM d, yyyy h:mm a')}</span>}
```
